name: Python package

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test_conda:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.6", "3.7", "3.8"]
    steps:
      - uses: actions/checkout@v1
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda bash
        shell: bash -l {0}
        run: export CONDA_ALWAYS_YES="true" && conda env create --file conda-envs/mols.yml && conda activate    mols_test && pip install . pytest
      - name: pytest
        shell: bash -l {0}
        run: conda activate mols_test && python setup.py test
